### ISSUE TITLE
Error thrown when checking an expired certificate

### ISSUE THREAD

**Issue by nekloth** [rheh/ssl-date-checker#1]
Instead of having a JSON message in case of expiration, I have an error message : 
```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: certificate has expired
    at TLSSocket.<anonymous> (_tls_wrap.js:1098:38)
    at emitNone (events.js:105:13)
    at TLSSocket.emit (events.js:207:7)
    at TLSSocket._finishInit (_tls_wrap.js:628:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:458:38)
```

I could be nice to have the information in a JSON format (to be implemented in Node-Red for instance).

**Comment by nekloth** [comment]
Tested with https://expired.badssl.com and works perfectly.

Thank you !
